"use client";

import { useEffect, useState } from "react";
import { Loader2, Users } from "lucide-react";

export default function ProjectCrewPanel({ projectId }) {
  const [members, setMembers] = useState([]); const [selected, setSelected] = useState([]);
  const [primaryId, setPrimaryId] = useState(null); const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [saved, setSaved] = useState(false);
  useEffect(() => { (async () => { try { const [teamResponse, crewResponse] = await Promise.all([fetch("/api/team-members"), fetch(`/api/admin/project-crew?project_id=${projectId}`)]); const team = await teamResponse.json(); const crew = await crewResponse.json(); if (!teamResponse.ok || !crewResponse.ok) throw new Error(crew.error || "Could not load crew"); setMembers((Array.isArray(team) ? team : []).filter((member) => member.status === "active")); setSelected((crew.crew || []).map((member) => Number(member.team_member_id))); setPrimaryId(Number(crew.primary_painter_id) || null); } catch (cause) { setError(cause.message); } finally { setLoading(false); } })(); }, [projectId]);
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : [...current, id]);
  const save = async () => { setSaving(true); setError(""); setSaved(false); try { const response = await fetch("/api/admin/project-crew", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project_id: projectId, team_member_ids: selected }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not save crew"); setSaved(true); } catch (cause) { setError(cause.message); } finally { setSaving(false); } };
  return <section className="rounded-lg border border-slate-200 p-4"><div className="flex items-center gap-2"><Users size={18} className="text-amber-600" /><div><h3 className="font-semibold text-slate-900">Assigned crew</h3><p className="text-sm text-slate-600">The primary painter and selected crew can access this job in Today.</p></div></div>{loading ? <p className="mt-3 text-sm text-slate-500">Loading crew…</p> : <div className="mt-4 grid gap-2 sm:grid-cols-2">{members.map((member) => <label key={member.id} className={`flex items-center gap-3 rounded-lg border p-3 ${primaryId === member.id ? "border-amber-300 bg-amber-50" : "border-slate-200"}`}><input type="checkbox" checked={primaryId === member.id || selected.includes(member.id)} disabled={primaryId === member.id} onChange={() => toggle(member.id)} /><span className="min-w-0"><span className="block font-medium text-slate-900">{member.name}</span><span className="block truncate text-xs text-slate-500">{primaryId === member.id ? "Primary painter" : member.role}</span></span></label>)}</div>}{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-4 flex items-center gap-3"><button type="button" onClick={save} disabled={loading || saving} className="flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving && <Loader2 size={15} className="animate-spin" />}Save crew</button>{saved && <span className="text-sm font-semibold text-green-700">Crew saved</span>}</div></section>;
}
